-- DROP the tables and constraints
DROP TABLE IF EXISTS users_messages;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS channels;
DROP TABLE IF EXISTS channel_members;

-- create the messages table with the foreign key
CREATE TABLE messages (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  message_body VARCHAR NOT NULL,
  author_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  recipient_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT now() NOT NULL
);